CPU:
  type: MpstatCommandMonitor
  publish_rate: 0.2
  items:
    - User
    - Nice
    - Sys
    - IOwait
    - IRQ
    - SoftIRQ
    - Steal
    - Guest
    - Gnice
    - Idle
ProcessCpu:
  type: PsCommandMonitor
  publish_rate: 0.2
  sort_key: UseCpuRate
  num_to_disp: 5
  items:
    - UserID
    - ProcessID
    - UseCpuRate
    - UseMemoryRate
    - UseVirtualMemorySize
    - UsePhisicalMemorySize
    - TypeOfTerminal
    - ProcessStatus
    - ProcessStartTime
    - ExecutionTime
    - ExecutionCommand
ProcessMemory:
  type: PsCommandMonitor
  publish_rate: 0.2
  sort_key: UseMemoryRate
  num_to_disp: 5
  items:
    - UserID
    - ProcessID
    - UseCpuRate
    - UseMemoryRate
    - UseVirtualMemorySize
    - UsePhisicalMemorySize
    - TypeOfTerminal
    - ProcessStatus
    - ProcessStartTime
    - ExecutionTime
    - ExecutionCommand
Memory:
  type: MeminfoCommandMonitor
  publish_rate: 0.1
  items:
    - MemTotal
    - MemFree
    - MemAvailable
    - Buffers
    - Cached
    - SwapCached
    - Active
    - Inactive
    - Active(anon)
    - Inactive(anon)
    - Active(file)
    - Inactive(file)
    - Unevictable
    - Mlocked
    - SwapTotal
    - SwapFree
    - Dirty
    - Writeback
    - AnonPages
    - Mapped
    - Shmem
    - Slab
    - SReclaimable
    - SUnreclaim
    - KernelStack
    - PageTables
    - NFS_Unstable
    - Bounce
    - WritebackTmp
    - CommitLimit
    - Committed_AS
    - VmallocTotal
    - VmallocUsed
    - VmallocChunk
    - HardwareCorrupted
    - AnonHugePages
    - HugePages_Total
    - HugePages_Free
    - HugePages_Rsvd
    - HugePages_Surp
    - Hugepagesize
    - DirectMap4k
    - DirectMap2M
    - DirectMap1G
Sensors:
  type: SensorsCommandMonitor
  publish_rate: 0.1
  items:
    - temp
    - in
    - fan
Disk:
  type: DfCommandMonitor
  publish_rate: 0.01
  target:
    - "/"
  items:
    - Filesystem
    - Size
    - Used
    - Avail
    - Use%
Network:
  type: NetstatCommandMonitor
  publish_rate: 0.1
  target:
    - wlan0
    - wlp3s0
  items: 
    - Interface
    - MTU
    - ReceiveOK
    - ReceiveERR
    - ReceiveDRP
    - ReceiveOVR
    - SendOK
    - SendERR
    - SendDRP
    - SendOVR
    - Flg
USB:
  type: LsusbCommandMonitor
  publish_rate: 0.1
  device: 0000:0000
  grep_match : [iSerial, $SERIAL_KEY]
DeviceAdm:
  type: UdevAdmCommandMonitor
  publish_rate: 0.1
  device: /dev/tty0
Wireless:
  type: IwconfigCommandMonitor
  publish_rate: 0.2
  items:
    - IEEE
    - ESSID
    - Nickname
    - Mode
    - Frequency
    - AccessPointMac
    - BitRate
    - TxPower
    - Sensitivity
    - RetryMinLimit
    - RTSThr
    - FragmentThr
    - PowerManagement
    - LinkQuality
    - SignalLevel
    - NoiseLevel
    - RxInvalidNwid
    - InvalidCrypt
    - RxInvalidFrag
    - TxExcessiveRetries
    - InvalidMisc
    - MissedBeacon
File:
  type: FileMonitor
  publish_rate: 0.0
  files:
    StereoCameraConfig:
      - path: "/etc/opt/tmc/robot/conf.d/stereo_pgr_camera.yml"
        notcontain: ["- id: 13451964", "- id: 13451965"]
        error_message: "Camera setting file is default. Please execute '$ hsrb_command restore'."
